"""Exception codes and deterministic reason codes.

Both enums are part of the contract. A code is a stable identifier that an
evaluator can grade against and a person can look up. Neither is free text, and
neither is generated by a model.
"""

from collections.abc import Iterable
from enum import StrEnum


class ExceptionCode(StrEnum):
    """Why a settlement line could not simply be resolved."""

    MISSING_PAYMENT = "MISSING_PAYMENT"
    """A settlement line refers to a payment that no source fact describes."""

    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"
    """A payment was captured but no settlement line covers it, past the point
    where one was expected."""

    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    """Amounts that should agree do not, and both sides are known."""

    FEE_MISMATCH = "FEE_MISMATCH"
    """The fee or tax component disagrees with what the net implies."""

    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    """Two records that must be in one currency are not."""

    DUPLICATE_CONFLICT = "DUPLICATE_CONFLICT"
    """The same idempotency identity arrived with a different payload hash."""

    OUT_OF_ORDER_EVENT = "OUT_OF_ORDER_EVENT"
    """An event's occurred-at contradicts the sequence it belongs to, for
    example a refund dated before its capture."""

    PARTIAL_REFUND = "PARTIAL_REFUND"
    """A refund covers part of a capture, so the remaining balance still has to
    be accounted for. Recorded as an exception because it needs a human view,
    not because anything is wrong."""

    TIMING_PENDING = "TIMING_PENDING"
    """Nothing is wrong yet. The settlement is inside its expected window and
    has simply not arrived."""

    UNMAPPED_REFERENCE = "UNMAPPED_REFERENCE"
    """A reference exists but points at nothing this system knows about."""

    MALFORMED_RECORD = "MALFORMED_RECORD"
    """The source record could not be read into the canonical model at all."""

    UNSUPPORTED_STATE = "UNSUPPORTED_STATE"
    """The records are coherent but describe a case the contract does not yet
    cover. Recorded honestly rather than forced into a nearby code."""

    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    """The evidence admits more than one explanation. Not a mismatch."""


class ReasonCode(StrEnum):
    """The deterministic reason a decision reached its status.

    A reason code says which rule fired. It is never a sentence, never
    model-generated, and never an explanation of intent.
    """

    ALL_REQUIRED_INVARIANTS_PASSED = "ALL_REQUIRED_INVARIANTS_PASSED"
    NET_FORMULA_MISMATCH = "NET_FORMULA_MISMATCH"
    PAYOUT_TOTAL_MISMATCH = "PAYOUT_TOTAL_MISMATCH"
    RETURNS_EXCEED_CAPTURE = "RETURNS_EXCEED_CAPTURE"
    CURRENCY_NOT_UNIFORM = "CURRENCY_NOT_UNIFORM"
    PAYLOAD_HASH_CONFLICT = "PAYLOAD_HASH_CONFLICT"
    SOURCE_FACT_REWRITE_ATTEMPTED = "SOURCE_FACT_REWRITE_ATTEMPTED"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    EVIDENCE_NOT_LINKED = "EVIDENCE_NOT_LINKED"
    REQUIRED_INVARIANT_FAILED = "REQUIRED_INVARIANT_FAILED"
    REQUIRED_INVARIANT_NOT_EVALUATED = "REQUIRED_INVARIANT_NOT_EVALUATED"
    REQUIRED_INVARIANT_MISSING_INPUT = "REQUIRED_INVARIANT_MISSING_INPUT"
    SETTLEMENT_WITHIN_EXPECTED_WINDOW = "SETTLEMENT_WITHIN_EXPECTED_WINDOW"
    NO_APPLICABLE_RETURN_EVENTS = "NO_APPLICABLE_RETURN_EVENTS"


#: Exception codes ordered from the one that must win to the one that yields to
#: everything else.
#:
#: The order encodes three rules from the contract. Data that is malformed or
#: self-contradicting outranks every interpretation of it, so a broken record
#: can never be quietly reported as a clean match. A settlement that is merely
#: late is the weakest signal of all, because nothing is wrong with it yet.
#: Missing evidence sits just above it: it is not a mismatch, and it must not be
#: dressed up as one.
EXCEPTION_PRECEDENCE: tuple[ExceptionCode, ...] = (
    ExceptionCode.MALFORMED_RECORD,
    ExceptionCode.DUPLICATE_CONFLICT,
    ExceptionCode.UNSUPPORTED_STATE,
    ExceptionCode.CURRENCY_MISMATCH,
    ExceptionCode.OUT_OF_ORDER_EVENT,
    ExceptionCode.UNMAPPED_REFERENCE,
    ExceptionCode.AMOUNT_MISMATCH,
    ExceptionCode.FEE_MISMATCH,
    ExceptionCode.MISSING_PAYMENT,
    ExceptionCode.MISSING_SETTLEMENT,
    ExceptionCode.PARTIAL_REFUND,
    ExceptionCode.INSUFFICIENT_EVIDENCE,
    ExceptionCode.TIMING_PENDING,
)

_PRECEDENCE_RANK: dict[ExceptionCode, int] = {
    code: rank for rank, code in enumerate(EXCEPTION_PRECEDENCE)
}


def precedence_rank(code: ExceptionCode) -> int:
    """Return the rank of a code, where a lower number wins."""
    return _PRECEDENCE_RANK[code]


def highest_precedence(codes: Iterable[ExceptionCode]) -> ExceptionCode | None:
    """Return the code that decides the outcome, or None for an empty input."""
    ranked = sorted(codes, key=precedence_rank)
    return ranked[0] if ranked else None
